### ISSUE TITLE
runtime error 217

### ISSUE THREAD

**Issue by GabrielOnDelphi** [DeveloppeurPascal/Delphi-Game-Engine#95]
runtime error 217

**Comment by DeveloppeurPascal** [comment]
Hi Gabriel
What Delphi release do you use ?

**Comment by DeveloppeurPascal** [comment]
no answer, can't fix a problem with no precision : what program used, what delphi release, what framework ?
the 217 error can be many things like missing DLL in a program or SDK not linked
